---
ansible_ssh_user: USERNAME
ansible_ssh_private_key_file: PRIVATE_KEY_FILE
ansible_ssh_host: HOSTADDR
# vars of setup-wireguard role
wireguard_address: 10.10.1.1/24
wireguard_listen_port: 55432
wireguard_peers:
  - name: Client 1
    public_key: REDACTED PUBLIC KEY
    allowed_ips: 10.10.1.2/32

# vars of setup-dante role
dante_internal_port: 1080
dante_internal_interface: wg0
dante_external_interface: "{{ ansible_default_ipv4.interface }}"
dante_ip_subnet_from: 10.10.1.0/24
